import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';
const ctx=vm.createContext({});vm.runInContext(readFileSync(new URL('../public/contact-message.js',import.meta.url),'utf8'),ctx);
test('WhatsApp message contains all supplied form details and survives URL encoding',()=>{const fields={name:'테스트 & Guest',email:'guest@example.com',date:'2026-10-01',time:'07:00',people:'2',plan:'3 sessions — IDR 1,200,000',total:'IDR 2,400,000',level:'Beginner',phone:'+62 800 1234',message:'Hello?\nA&B #surf 🏄'};for(const lang of ['en','ko','ja']){const text=ctx.buildWhatsAppInquiry(fields,lang);for(const value of Object.values(fields))assert.ok(text.includes(value));const url=new URL('https://wa.me/6287861136585?text='+encodeURIComponent(text));assert.equal(url.searchParams.get('text'),text);assert.equal(url.searchParams.size,1);}});

test('WhatsApp links support the installed app, universal link and web fallback',()=>{const text='HELLO SEA · 문의\nA&B';const links=ctx.buildWhatsAppLinks('+62 878-6113-6585',text);assert.equal(links.app,`whatsapp://send?phone=6287861136585&text=${encodeURIComponent(text)}`);assert.equal(links.universal,`https://wa.me/6287861136585?text=${encodeURIComponent(text)}`);assert.equal(links.web,`https://web.whatsapp.com/send?phone=6287861136585&text=${encodeURIComponent(text)}`);});


test('Only the detail-aware WhatsApp action remains and it uses the full-message universal link',()=>{const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');const app=readFileSync(new URL('../public/app.js',import.meta.url),'utf8');const form=html.match(/<form id="inquiry-form"[\s\S]*?<\/form>/)?.[0]||'';assert.ok(form.includes('id="form-whatsapp-send"'));assert.ok(!html.includes('id="whatsapp"'));assert.ok(!html.includes('data-whatsapp="true"'));assert.match(app,/openInquiryWhatsApp\(inquiryWhatsAppText\(\)\)/);assert.match(app,/window\.location\.href=links\.universal/);assert.ok(!app.includes('window.location.href=links.app'));});

test('Inquiry form offers hourly Lombok times from 05:00 through 16:00',()=>{const html=readFileSync(new URL('../public/index.html',import.meta.url),'utf8');const form=html.match(/<form id="inquiry-form"[\s\S]*?<\/form>/)?.[0]||'';assert.ok(form.includes('name="preferredTime"'));const values=[...form.matchAll(/<option value="(\d{2}:00)">/g)].map(match=>match[1]);assert.deepEqual(values,['05:00','06:00','07:00','08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00']);});