import fallback from '../public/pricing.json' with {type:'json'};
import {db} from './content.js';
export const ids=['group','private','guiding','three','five'];
export const uuid=x=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(x);
export function validDate(x){return typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x;}
export function validatePrices(x){if(!Array.isArray(x)||x.length!==5)return null;const result=[];for(const id of ids){const p=x.find(p=>p?.id===id);if(!p||!Number.isSafeInteger(p.price)||p.price<0||p.price>100000000)return null;result.push({...fallback.find(p=>p.id===id),price:p.price});}return result;}
export async function getPrices(){const r=await db('site_content?id=eq.pricing&select=content');if(!r.ok)throw Error('Price lookup failed');const rows=await r.json();const prices=rows.length?validatePrices(rows[0].content):fallback;if(!prices)throw Error('Invalid stored prices');return prices;}
function raster(src){if(typeof src!=='string')return false;if(/^\/assets\/[a-zA-Z0-9_./-]+\.(jpg|jpeg|png|webp)$/.test(src)&&!src.includes('..'))return true;const m=src.match(/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/]+={0,2})$/);if(!m)return false;const b=Buffer.from(m[2],'base64');if(b.length>260000||b.toString('base64')!==m[2])return false;return m[1]==='jpeg'?b[0]===255&&b[1]===216&&b[2]===255:m[1]==='png'?b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP';}
export function validateGallery(x){if(!Array.isArray(x)||x.length<1||x.length>12||Buffer.byteLength(JSON.stringify(x))>2800000)return null;const seen=new Set();const out=[];for(const p of x){if(!p||!/^[a-z0-9-]{1,60}$/.test(p.id)||seen.has(p.id)||!raster(p.src)||!['surf','scenery'].includes(p.category))return null;seen.add(p.id);const q={id:p.id,src:p.src,category:p.category,featured:p.featured===true};for(const key of ['title','location','alt']){q[key]={};for(const l of ['en','ko','ja']){const t=p[key]?.[l];if(typeof t!=='string'||!t.trim()||t.length>240)return null;q[key][l]=t.trim();}}for(const key of ['author','license','source','licenseUrl','originalTitle','changes','date']){const v=p[key]||'';if(typeof v!=='string'||v.length>500)return null;if(['source','licenseUrl'].includes(key)&&v){try{if(new URL(v).protocol!=='https:')return null;}catch{return null;}}q[key]=v;}out.push(q);}if(out.filter(p=>p.featured).length!==1)return null;return out;}
export function validateBooking(x){if(!x||!uuid(x.id)||!validDate(x.date)||!Number.isInteger(x.session)||x.session<1||x.session>4||!Number.isInteger(x.people)||x.people<1||x.people>50||!['pending','confirmed','completed','cancelled'].includes(x.status)||!['',...ids].includes(x.plan)||x.inquiry_id&&!uuid(x.inquiry_id))return null;const out={id:x.id,date:x.date,session:x.session,people:x.people,status:x.status,plan:x.plan,inquiry_id:x.inquiry_id||null};for(const [k,max] of Object.entries({name:100,participant_names:2000,time:50,phone:100,notes:2000})){if(typeof x[k]!=='string'||x[k].length>max)return null;out[k]=x[k].trim();}return out.name?out:null;}
