import {createHmac} from 'node:crypto';
import {allowedOrigins,configured} from '../lib/config.js';
import {adminAllowed,getUser,mutationAllowed} from '../lib/auth.js';
import {db,serverHeaders} from '../lib/content.js';
import {REVIEW_ADMIN_PAGE_SIZE,REVIEW_BUCKET,REVIEW_PAGE_SIZE,reviewPage,reviewPaths,validateReviewSubmission} from '../lib/reviews.js';

const uuid=x=>typeof x==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x);
const base=()=>process.env.SUPABASE_URL.replace(/\/$/,'');
const encodePath=value=>value.split('/').map(encodeURIComponent).join('/');
const storageUrl=(path)=>`${base()}/storage/v1/${path}`;
async function body(req,max=30000){let value=req.body;if(typeof value==='string')value=JSON.parse(value);if(!value||Buffer.byteLength(JSON.stringify(value))>max)throw Error('invalid');return value;}
async function storage(path,options={}){return fetch(storageUrl(path),{...options,headers:{...serverHeaders(),...options.headers},signal:AbortSignal.timeout(10000)});}
function publicStorageUrl(value){if(/^https:\/\//.test(value))return value;return storageUrl(value.startsWith('/')?value.slice(1):value);}
async function signUpload(path){const r=await storage(`object/upload/sign/${REVIEW_BUCKET}/${encodePath(path)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({upsert:true})});if(!r.ok)throw Error('sign upload');const data=await r.json(),url=data.url||data.signedURL||data.signedUrl;if(!url)throw Error('sign upload');return publicStorageUrl(url);}
async function signRead(path){const r=await storage(`object/sign/${REVIEW_BUCKET}/${encodePath(path)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});if(!r.ok)throw Error('sign read');const data=await r.json(),url=data.signedURL||data.signedUrl||data.url;if(!url)throw Error('sign read');return publicStorageUrl(url);}
async function objectExists(path){const url=storageUrl(`object/authenticated/${REVIEW_BUCKET}/${encodePath(path)}`),options={headers:serverHeaders(),signal:AbortSignal.timeout(10000)};let r=await fetch(url,{...options,method:'HEAD'});if(r.status===405)r=await fetch(url,{...options,headers:{...options.headers,Range:'bytes=0-0'}});return r.ok;}
async function rowsWithMedia(rows){if(!rows.length)return rows;const ids=rows.map(x=>x.id).join(','),r=await db(`website_review_media?review_id=in.(${ids})&upload_complete=eq.true&select=id,review_id,sort_order,original_path,preview_path,width,height&order=sort_order`);if(!r.ok)throw Error('media lookup');const media=await r.json();await Promise.all(media.map(async item=>{[item.original_url,item.preview_url]=await Promise.all([signRead(item.original_path),signRead(item.preview_path)]);delete item.original_path;delete item.preview_path;}));return rows.map(row=>({...row,media:media.filter(item=>item.review_id===row.id)}));}
async function publicReviews(query,res){const kind=query.get('kind')||'photo';if(kind==='photo'){const r=await db('website_reviews?status=eq.published&media_count=gt.0&select=id,created_at,published_at,display_name,body,body_en,locale,media_count&order=published_at.desc&limit=24');if(!r.ok)throw Error('review lookup');return res.status(200).json({rows:await rowsWithMedia(await r.json())});}
 if(kind!=='text')return res.status(400).json({error:'Invalid review list.'});const page=reviewPage(query.get('page')),offset=(page-1)*REVIEW_PAGE_SIZE,r=await db(`website_reviews?status=eq.published&media_count=eq.0&select=id,created_at,published_at,display_name,body,body_en,locale&order=published_at.desc&limit=${REVIEW_PAGE_SIZE}&offset=${offset}`,{headers:{Prefer:'count=exact'}});if(!r.ok)throw Error('review lookup');const range=r.headers.get('content-range')||'',total=Number(range.split('/')[1]||0);return res.status(200).json({rows:await r.json(),page,pageSize:REVIEW_PAGE_SIZE,total,pages:Math.max(1,Math.ceil(total/REVIEW_PAGE_SIZE))});}
async function adminReviews(req,query,res){const user=await getUser(req);if(!user)return res.status(401).json({error:'다시 로그인해주세요.'});if(!adminAllowed(user))return res.status(403).json({error:'관리자 권한이 필요합니다.'});const status=query.get('status')||'pending',offset=Number(query.get('offset')||0);if(!['pending','published','rejected'].includes(status)||!Number.isSafeInteger(offset)||offset<0)return res.status(400).json({error:'조회 조건을 확인해주세요.'});const r=await db(`website_reviews?status=eq.${status}&select=id,created_at,published_at,display_name,body,body_en,locale,media_count&order=created_at.desc&limit=${REVIEW_ADMIN_PAGE_SIZE}&offset=${offset}`);if(!r.ok)throw Error('admin lookup');const rows=await rowsWithMedia(await r.json());return res.status(200).json({rows,hasNext:rows.length===REVIEW_ADMIN_PAGE_SIZE,pageSize:REVIEW_ADMIN_PAGE_SIZE});}
async function createReview(req,res,value){if(!mutationAllowed(req))return res.status(403).json({error:'Please use the HELLO SEA review form.'});const checked=validateReviewSubmission(value);if(!checked)return res.status(400).json({error:'Please check your review and photos.'});const ip=process.env.VERCEL?String(req.headers['x-vercel-forwarded-for']||'unknown').split(',')[0].trim():(req.socket?.remoteAddress||'local'),clientHash=createHmac('sha256',process.env.RATE_LIMIT_SECRET).update(ip).digest('hex');const payload={...checked};delete payload.media;const rpc=await db('rpc/submit_website_review',{method:'POST',body:JSON.stringify({payload,client_hash:clientHash})});if(!rpc.ok)throw Error('submit');const result=await rpc.json();if(result?.status==='limited'){res.setHeader('Retry-After','3600');return res.status(429).json({error:'You have submitted several reviews. Please try again later.'});}if(result?.status!=='accepted'||!uuid(result.review_id))throw Error('submit');const reviewId=result.review_id,existing=await db(`website_reviews?id=eq.${reviewId}&select=status`);if(!existing.ok)throw Error('review state');const state=(await existing.json())[0]?.status;if(state!=='uploading')return res.status(201).json({ok:true,submitted:true});
 await db(`website_review_media?review_id=eq.${reviewId}`,{method:'DELETE'});const media=checked.media.map((item,index)=>{const paths=reviewPaths(reviewId,index,item.mimeType);return {review_id:reviewId,sort_order:index,original_path:paths.original,preview_path:paths.preview,mime_type:item.mimeType,original_size:item.size,preview_size:item.previewSize,width:item.width,height:item.height,upload_complete:false};});if(media.length){const saved=await db('website_review_media',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(media)});if(!saved.ok)throw Error('media rows');}
 const uploads=await Promise.all(media.map(async item=>({index:item.sort_order,originalUrl:await signUpload(item.original_path),previewUrl:await signUpload(item.preview_path)})));return res.status(201).json({ok:true,reviewId,uploads,submitted:false});}
async function finalizeReview(req,res,value){if(!mutationAllowed(req)||!uuid(value.requestId))return res.status(400).json({error:'Please check the review submission.'});const r=await db(`website_reviews?request_id=eq.${value.requestId}&select=id,status,media_count`);if(!r.ok)throw Error('review lookup');const review=(await r.json())[0];if(!review)return res.status(404).json({error:'Review submission not found.'});if(review.status!=='uploading')return res.status(200).json({ok:true});const m=await db(`website_review_media?review_id=eq.${review.id}&select=id,original_path,preview_path`);if(!m.ok)throw Error('media lookup');const media=await m.json();if(media.length!==review.media_count)return res.status(409).json({error:'Photo upload is incomplete.'});const checks=await Promise.all(media.flatMap(item=>[objectExists(item.original_path),objectExists(item.preview_path)]));if(checks.some(x=>!x))return res.status(409).json({error:'Photo upload is incomplete.'});const mediaDone=await db(`website_review_media?review_id=eq.${review.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({upload_complete:true})}),reviewDone=await db(`website_reviews?id=eq.${review.id}&status=eq.uploading`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status:'pending'})});if(!mediaDone.ok||!reviewDone.ok)throw Error('finalize');return res.status(200).json({ok:true});}
async function moderate(req,res,value){if(!mutationAllowed(req)||!uuid(value.id)||!['published','rejected'].includes(value.status))return res.status(400).json({error:'리뷰 상태를 확인해주세요.'});const user=await getUser(req);if(!user)return res.status(401).json({error:'다시 로그인해주세요.'});if(!adminAllowed(user))return res.status(403).json({error:'관리자 권한이 필요합니다.'});const update={status:value.status,reviewed_at:new Date().toISOString(),reviewed_by:user.id,published_at:value.status==='published'?new Date().toISOString():null},r=await db(`website_reviews?id=eq.${value.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(update)});if(!r.ok)throw Error('moderate');const rows=await r.json();return res.status(rows.length?200:404).json(rows.length?{ok:true}:{error:'리뷰를 찾지 못했습니다.'});}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!['GET','POST','PATCH'].includes(req.method))return res.status(405).json({error:'Method not allowed.'});if(!configured())return res.status(503).json({error:'Review service is not configured.'});const query=new URL(req.url,'https://localhost').searchParams;try{if(req.method==='GET')return query.get('admin')==='1'?adminReviews(req,query,res):publicReviews(query,res);const value=await body(req);if(req.method==='PATCH')return moderate(req,res,value);return value.action==='finalize'?finalizeReview(req,res,value):createReview(req,res,value);}catch{return res.status(503).json({error:'We could not complete the review request. Please try again.'});}}
